# Generated by Django 2.0.6 on 2018-06-13 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easysensor', '0002_easysensor_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='easysensor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='easysensors', to=settings.AUTH_USER_MODEL),
        ),
    ]
