# Generated by Django 2.0.6 on 2018-06-13 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('easysensor', '0003_auto_20180613_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('speed', models.IntegerField(null=True)),
                ('rpm', models.IntegerField(null=True)),
                ('maf', models.IntegerField(null=True)),
                ('load', models.IntegerField(null=True)),
                ('acceleration', models.FloatField(null=True)),
                ('lacet', models.IntegerField(null=True)),
                ('count', models.IntegerField()),
                ('vitesse_limite', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateTimeField()),
                ('vitesse_moyenne', models.FloatField(null=True)),
                ('duree', models.CharField(max_length=250, null=True)),
                ('puissance', models.FloatField(null=True)),
                ('distance', models.FloatField(null=True)),
                ('note_eco', models.FloatField(null=True)),
                ('note_secu', models.FloatField(null=True)),
                ('note_conf', models.FloatField(null=True)),
                ('note_vit', models.FloatField(null=True)),
                ('note_glob', models.FloatField(null=True)),
                ('easysensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easysensor.EasySensor')),
            ],
        ),
        migrations.AddField(
            model_name='mesure',
            name='trajet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trajet.Trajet'),
        ),
    ]
