# Generated by Django 2.0.6 on 2018-06-13 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trajet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trajet',
            name='puissance',
        ),
    ]
