# Generated by Django 2.0.6 on 2018-06-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trajet', '0002_remove_trajet_puissance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trajet',
            name='vitesse_moyenne',
        ),
    ]
