# Generated by Django 2.0.6 on 2018-06-13 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trajet', '0003_remove_trajet_vitesse_moyenne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesure',
            name='trajet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesures', to='trajet.Trajet'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='easysensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajets', to='easysensor.EasySensor'),
        ),
    ]
